[[redirects]]
	from = "/shannon/:slug"
	to = "/:slug"
	status = 200
	force = true

[[redirects]]
	from = "/presentations/:slug"
	to = "/:slug"
	status = 200
	force = true

[[redirects]]
	from = "/publications/:slug"
	to = "/:slug"
	status = 200
	force = true

[[redirects]]
	from = "/projects/:slug"
	to = "/:slug"
	status = 200
	force = true